# Generated by Django 4.0.4 on 2022-06-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(null=b'I01\n', upload_to='productos'),
            preserve_default=b'I01\n',
        ),
    ]
