# Generated by Django 4.0.4 on 2022-06-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_accesorio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
