# Generated by Django 4.0.4 on 2022-06-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_accesorio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
