# Generated by Django 4.0.4 on 2022-06-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_accesorio_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('region', models.IntegerField(choices=[(1, 'Metropolitana'), (2, 'Valparaiso'), (3, 'Bio-Bio')])),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
    ]
