# Generated by Django 4.0.4 on 2022-06-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_alter_cliente_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.IntegerField(choices=[(1, 'Maipu'), (2, 'Cerrillos'), (3, 'Independencia')], default=1),
        ),
    ]
