# Generated by Django 4.0.4 on 2022-06-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_cliente_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comuna',
            field=models.IntegerField(choices=[(4, 'Maipu'), (5, 'Cerrillos'), (6, 'Independencia')]),
        ),
    ]
