# Generated by Django 4.0.4 on 2022-06-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_alter_cliente_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comuna',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='region',
            field=models.IntegerField(),
        ),
    ]
